### ISSUE TITLE
Ruby and Rails are out of date

### ISSUE THREAD

**Issue by tmornini** [subledger/PlugNPlay#1]
Let's update to Rails current (4.0.2) and Ruby current (2.1.0)

**Comment by michetti** [comment]
Hey @tmornini, I have already updated both Rails and Ruby on the Granular branch. 
This atpay branch does not have the newest code yet.

I will merge Granular branch to head and then merge the improvements to atpay branch, ok?

**Comment by tmornini** [comment]
OK, thanks!
